#+title: Product Backlog
#+options: date:nil toc:nil author:nil num:nil
#+tags: { reviewing(r) }
#+tags: { story(s) epic(e) }

* Stories

This document contains the [[http://www.mountaingoatsoftware.com/agile/scrum/product-backlog][product backlog]] for Qart.

** To be prioritised

*** Implement Qart.Wheels Automation using Pipeline processor         :story:

Now that we have a pipeline processor we need to make use of it to
test Qart.Wheels.

*** Add support for Test Case description                             :story:

Tests at present do not have a human-readable description associated
with them. We should create a new file type =.description= that when
present gets read and populates a property in the test case
=Description=. The description file should be a JSON object with
KVPs. Some of these will be well-known keys (such as perhaps
"description" or maybe "summary") others can be user defined and used
only in the user specific processors.

*** Remove test app                                                   :story:

Once Qart.Wheels is done we don't need it.

*** Actions should support parameters                                 :story:

At present there is no way to supply additional parameters to
actions. We need to implement this to support two use cases:

URL style notation:

: MyProcessor {
:      "actions" : [
:          "an_action",          => no parameters
:          "another_action?param1=/a/b&param2=abc
: ...

JSON style notation:

: MyProcessor {
:        "actions" : [
:            "an_action",
:            "another_action" {
:                "param1" : "/a/b",
:                "param2" : "abc",
: ...
We need to support both of these forms.

*** Add endpoints to Qart.Wheels                                      :story:

Useful endpoints:

- list all test cases with descriptions
- run test cases: with argument of starting point
- ability to supply options as argument

*** Add Rebaseline to Test Case Context                               :story:

Propagate the command line flag into the context.

*** Split workflow from testing in Qart.Testing                       :story:
*** Add help to cybertester describing all available actions          :story:

When an action is registered it must register a description which is
used to produce the help text. Must document inputs and outputs.

Same with processor.

*** Rename manual to cookbook                                         :story:

This is not an exhaustive manual, just a quick started guide.

*** Add examples to manual                                            :story:

Document =Qart.Wheels.TestAutomation= as an example in manual.

*** Split inputs from outputs in test                                 :story:

FIXME: deferred.

Create a folder for expectations: =expected=, =exp=, =assets=

Different kinds of data:

- actions:
  - action instance (meta-data, .test)
  - |

- meta-data: .test,
- data: inputs

*** Merge .transform with .test                                       :story:

Put all the arguments into .test (remove .ref, .transform,
.exclude.xpath) as arguments to the action.

*** Document .ref and .transform behaviours                           :story:

Manual needs to cover these.

*** Consider not having empty names with .extensions                  :story:

In UNIX (Linux, OSX), =.= is considered hidden. This makes it harder
to look at test cases.

*** =TestCaseContext= should have Qart specific information           :story:

These should be made available to the running test case:

- =TestSession=
- =TestCase=: a bit recursive?
- =Description=: for when we are building a description dynamically,
  adding values to keys;
- =Logger=

*** Consider changing the structure of .test file to make processor more obvious :epic:

The test description files start with a processor id, e.g.:

: MyProcessor { "a" : "b" }

This means we are calling =MyProcessor= and it understands parameter
=a= with a value of =b=. However, this is not obvious to a user. We
should look to see if there are more obvious ways to express this.

*** Consider merging description into =.test= file                    :story:

At present it is not obvious to users what exactly a test does. Even
when using the pipeline processor one can only see what the steps are,
not what their meaning is. For example, say a set of actions such as
("list files", "upload file", "remove file", "list files") do not tell
us anything about intent; a description such as "Given a new file,
when removing it the file is no longer part of the list of files"
would make the test case description much more readable.
*** .Test definiton file should support arbitrary tags                :story:

Add some JSON arguments for tagging tests.

*** Fix link to Contributing in Readme.                               :story:

Link is broken.

*** Add a test case discoverer                                        :story:

We should have a way to allow the user to supply user defined .test
files and to supply parsers for those files. We also need to add a
processor factory.
*** Semi-colon as a separator causes problems for some shells         :story:

Shells such as Powershell and Bash use semi-colon as a separator for
commands; this means we can only run Qart.CyberTester by escaping the
commands. We should try to use other separators such as =:=. We could
perhaps support both kinds.

*** Add support for token replacement                                 :story:

It would be good to have some machinery to replace given tokens in XML
and JSON files. Ideally it should also support post-processing such as
moving dates forward in time, etc.
